[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
